REPOSITORY=${1:-18735/check}
ALPINE_VERSION=${2:-3.12}
echo "${REPOSITORY}"
echo ${ALPINE_VERSION}
docker build -t ${REPOSITORY}:alpine-${ALPINE_VERSION} --build-arg ALPINE_VERSION=${ALPINE_VERSION} .
