version: 2.1
executors:
  python:
    docker:
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/python:3.6.1
  publisher:
    docker:
      - image: docker:18.06.0-ce
jobs:
  build:
    executor: publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker run --privileged linuxkit/binfmt:v0.6
      - attach_workspace:
          at: .
      - run: make build REPOSITORY="18375/alpine"
  build_alpine:
    executor: publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker run --privileged linuxkit/binfmt:v0.6
      - attach_workspace:
          at: .
      - run: make build REPOSITORY="18375/alpine" ALPINE_VERSION=3.12
  buiil_n_publish:
    executor: publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker run --privileged linuxkit/binfmt:v0.6
      - attach_workspace:
          at: .
      - run: apk add --no-cache make bash git
      - run: make build REPOSITORY="18375/alpine"
      - run: docker login -u "${DOCKER_REGISTRY_USER}" -p "${DOCKER_REGISTRY_PASSWORD}"
      - run: make push REPOSITORY="${DOCKER_REGISTRY}"
      - run: make manifest REPOSITORY="${DOCKER_REGISTRY}"
workflows:
  version: 2
  kubeyaml:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - build_alpine:
          filters:
            branches:
              ignore: master
      - buiil_n_publish:
          filters:
            branches:
              only: master
