version: 2.1
executors:
  python:
    docker:
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/python:3.6.1
  publisher:
    docker:
      - image: docker:18.06.0-ce
jobs:
  build:
    executor: publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker run --privileged linuxkit/binfmt:v0.6
      - attach_workspace:
          at: .
      - run: apk add make
      - run: make build REPOSITORY="183795"
  build_alpine:
    executor: publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker run --privileged linuxkit/binfmt:v0.6
      - attach_workspace:
          at: .
      - run: apk add make
      - run: make build REPOSITORY="183795" ALPINE_VERSION=3.7
  buiil_n_publish:
    executor: publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker run --privileged linuxkit/binfmt:v0.6
      - attach_workspace:
          at: .
      - run: apk add --no-cache make bash git
      - run: make build REPOSITORY="183795"
      - run: make build REPOSITORY="18375" ALPINE_VERSION=3.6
      - run: docker login -u 183795 -p Muthusana18
      - run: make push REPOSITORY="183795"
      - run: make manifest REPOSITORY="183795"
workflows:
  version: 2
  kubeyaml:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
      - build_alpine:
          filters:
            branches:
              ignore: main
      - buiil_n_publish:
          filters:
            branches:
              only: main
